version: "3"
services:
  db:
    image: bitnami/postgresql
    ports:
      - "${DB_PORT}:5432"
    enviroment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}